### ISSUE TITLE
Deep dependency

### ISSUE THREAD

**Issue by jensdietrich** [kay3-jaym3/SBOM-Benchmark#2]
Just looking at `[deep-dependency](https://github.com/kay3-jaym3/SBOM-Benchmark/tree/master/deep-dependency)
/pom.xml` in commit 38cf8e8 -- this still has the **direct** json dependency:

```xml
        <!-- vulnerable version of json.org (CVE-2022-45688) -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20220924</version>
        </dependency>
```

This should be an indirect (=deep) dependency !! 

Do this as follows: 

1. look for a project depending on (this version of) `org.json:json` -- [https://mvnrepository.com/artifact/org.json/json/usages](https://mvnrepository.com/artifact/org.json/json/usages) is a good starting point
2. confirm that the dependency you find depends on the version of `org.json:json` you want -- the link in 1 does not take versions into account, it lists downstream clients for *any* version
3. then replace the `org.json:json`  dependency by the one you find
4. confirm with `mvn dependency:tree` you should still see `org.json:json` as a leaf

**Comment by jensdietrich** [comment]
@kay3-jaym3   I don't seem to have the right to assign issues so I just tag you here

**Comment by kay3-jaym3** [comment]
This has been resolved @jensdietrich. The tika-parser module uses org.json so that it is a deep dependency. I just needed to remove the org.json direct dependency code but it has been updated now.

I have also proved this with the dependency tree, where the org.json module is one of the leaves of the tika-parser module.

<img width="603" alt="Screenshot 2024-06-07 at 3 40 20 PM" src="https://github.com/kay3-jaym3/SBOM-Benchmark/assets/122721803/54f8d7e3-a695-4ca9-b64a-f3e627e1bcaa">
<img width="603" alt="Screenshot 2024-06-07 at 3 40 24 PM" src="https://github.com/kay3-jaym3/SBOM-Benchmark/assets/122721803/e4a2aeba-1170-4809-abb9-6ef2d4841fd5">
